FROM node:22-alpine
WORKDIR /app
# Copy package.json and install dependencies
COPY . .
# COPY package.json ./
# COPY pnpm-lock.yaml ./
RUN npm i -g pnpm@latest-10
RUN pnpm install
# Copy the rest of the application code
#Prepare Nuxt project
RUN pnpm postinstall
# Build the Nuxt project
CMD ["pnpm", "dev"]
