/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAccordion: typeof import('primevue/accordion')['default']
    PAccordionContent: typeof import('primevue/accordioncontent')['default']
    PAccordionHeader: typeof import('primevue/accordionheader')['default']
    PAccordionPanel: typeof import('primevue/accordionpanel')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PBadge: typeof import('primevue/badge')['default']
    PButton: typeof import('primevue/button')['default']
    PChip: typeof import('primevue/chip')['default']
    PDeferredContent: typeof import('primevue/deferredcontent')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PEditor: typeof import('primevue/editor')['default']
    PForm: typeof import('@primevue/forms/form')['default']
    PInputGroup: typeof import('primevue/inputgroup')['default']
    PInputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenu: typeof import('primevue/menu')['default']
    PMessage: typeof import('primevue/message')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PSplitButton: typeof import('primevue/splitbutton')['default']
    PTab: typeof import('primevue/tab')['default']
    PTabList: typeof import('primevue/tablist')['default']
    PTabs: typeof import('primevue/tabs')['default']
    PTag: typeof import('primevue/tag')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
