/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PAccordion: typeof import('primevue/accordion')['default']
    PAccordionContent: typeof import('primevue/accordioncontent')['default']
    PAccordionHeader: typeof import('primevue/accordionheader')['default']
    PAccordionPanel: typeof import('primevue/accordionpanel')['default']
    PAvatar: typeof import('primevue/avatar')['default']
    PButton: typeof import('primevue/button')['default']
    PCheckbox: typeof import('primevue/checkbox')['default']
    PChip: typeof import('primevue/chip')['default']
    PDeferredContent: typeof import('primevue/deferredcontent')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PDrawer: typeof import('primevue/drawer')['default']
    PEditor: typeof import('primevue/editor')['default']
    PForm: typeof import('@primevue/forms/form')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMegaMenu: typeof import('primevue/megamenu')['default']
    PMenu: typeof import('primevue/menu')['default']
    PMessage: typeof import('primevue/message')['default']
    PSelect: typeof import('primevue/select')['default']
    PSelectButton: typeof import('primevue/selectbutton')['default']
    PSplitButton: typeof import('primevue/splitbutton')['default']
    PTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
